# Generated by Django 6.0.1 on 2026-03-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('ville_marche', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercant_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producteur_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite_initiale', models.PositiveBigIntegerField(default=0, verbose_name='Quantité totale prévue')),
                ('quantite_disponible', models.PositiveBigIntegerField(default=0, verbose_name='Reste disponible')),
                ('unite', models.CharField(choices=[('KG', 'Kilogramme'), ('TONNE', 'Tonne'), ('SAC', 'Sac')], default='KG', max_length=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='produits/')),
                ('statut_recolte', models.CharField(choices=[('SUR_PIED', '🌳 En cours de maturité (Sur pied)'), ('RECOLTE', '📦 Récolté et prêt')], default='SUR_PIED', max_length=20)),
                ('date_recolte_prevue', models.DateField(blank=True, null=True, verbose_name='Date de récolte prévue')),
                ('zone_production', models.CharField(choices=[('SIKASSO', 'Sikasso'), ('BAGUINEDA', 'Baguineda'), ('SEGOU', 'Segou')], default='SIKASSO', max_length=50)),
                ('zone_origine', models.CharField(max_length=100)),
                ('est_promotion', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('producteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='gestion_agro.producteur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_voulue', models.PositiveIntegerField(default=0)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('marche_destination', models.CharField(choices=[('MEDINE', 'Marché de Médine'), ('NIARÉLA', 'Marché de Niaréla'), ('DIBIDA', 'Marché de Dibida'), ('COURS_FLEUVE', 'Marché du Cours fleuve'), ('BOUGOBA', 'Marché de Bougoba')], default='MEDINE', max_length=50)),
                ('mode_paiement', models.CharField(choices=[('OM', 'Orange Money'), ('MOOV', 'Moov Money'), ('CASH', 'Espèces/Dépôt')], default='CASH', max_length=20)),
                ('ref_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_caution', models.CharField(choices=[('NON_PAYE', '❌ En attente'), ('PAYE', '✅ Payée')], default='NON_PAYE', max_length=20)),
                ('date_disponibilite', models.DateField(blank=True, null=True)),
                ('confirmation_producteur', models.BooleanField(default=False)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('caution_20', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.commercant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.produitagricole')),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Transporteur/Compagnie')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('vehicule', models.CharField(max_length=50, verbose_name='Type de véhicule (ex: Camion 10t)')),
                ('plaque_immatriculation', models.CharField(max_length=20, verbose_name='N° Plaque')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('tarif_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif de base (FCFA)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporteur_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee_estimee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_route', '🚛 En route'), ('livre', '✅ Livré')], default='en_attente', max_length=20)),
                ('frais_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.reservation')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_agro.transporteur')),
            ],
        ),
    ]
