# Generated by Django 6.0.1 on 2026-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producteur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='score_confiance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='video_demonstration',
            field=models.FileField(blank=True, null=True, upload_to='videos_produits/'),
        ),
    ]
