# Generated by Django 6.0.1 on 2026-04-16 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0003_avis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(max_length=100, verbose_name='Action effectuée')),
                ('localisation', models.CharField(max_length=255, verbose_name='Lieu actuel')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('code_tracabilite', models.CharField(editable=False, max_length=50, unique=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gestion_agro.livraison')),
            ],
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Description du problème')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False, verbose_name='Est résolu ?')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='gestion_agro.livraison')),
            ],
        ),
    ]
