# Generated by Django 6.0.1 on 2026-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0004_fluxproduit_litige'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils_transports/'),
        ),
    ]
