# Generated by Django 6.0.1 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0005_transporteur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercant',
            name='adresse_precise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='commercants/'),
        ),
        migrations.AddField(
            model_name='commercant',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
