# Generated by Django 6.0.1 on 2026-04-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0006_commercant_adresse_precise_commercant_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercant',
            name='adresse_precise',
        ),
        migrations.RemoveField(
            model_name='commercant',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='commercant',
            name='quartier',
        ),
    ]
