# Generated by Django 6.0.1 on 2026-05-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0007_remove_commercant_adresse_precise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Nouvelle notification', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('INFO', 'Info'), ('COMMANDE', 'Commande'), ('ALERTE', 'Alerte')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_systeme', to=settings.AUTH_USER_MODEL),
        ),
    ]
