# Generated by Django 6.0.1 on 2026-05-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0008_notification_titre_notification_type_notif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_chargement_reel',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chargement effectif au champ'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_livraison_reelle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Livraison effective au commerçant'),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='date_peremption_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de conservation'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_arrivee_estimee',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrivée estimée à destination'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Départ prévu du dépôt'),
        ),
    ]
