# Generated by Django 6.0.1 on 2026-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0011_alter_produitagricole_date_peremption_prevue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitagricole',
            name='date_peremption_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de conservation au champ'),
        ),
    ]
