# Generated by Django 6.0.1 on 2026-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0012_alter_produitagricole_date_peremption_prevue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxproduit',
            options={'ordering': ['-date_heure']},
        ),
        migrations.AddField(
            model_name='fluxproduit',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails supplémentaires'),
        ),
    ]
