# Generated by Django 6.0.1 on 2026-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0013_alter_fluxproduit_options_fluxproduit_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSecuriteRoutiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe_routier', models.CharField(help_text='Ex: Axe Ségou - Bamako', max_length=255)),
                ('type_incident', models.CharField(choices=[('BLOCAGE', 'Barrage / Blocage routier'), ('TENSION', 'Zone de forte tension'), ('PANNE', 'Incident logistique / Route impraticable')], max_length=20)),
                ('description_danger', models.TextField(help_text="Détails sur l'incident pour les chauffeurs")),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Alerte toujours en cours')),
            ],
        ),
    ]
