# Generated by Django 6.0.1 on 2026-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0014_alertesecuriteroutiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut_livraison',
            field=models.CharField(choices=[('A_EXPEDIER', 'À expédier'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré')], default='A_EXPEDIER', max_length=20, verbose_name="Statut d'expédition"),
        ),
    ]
