# Generated by Django 6.0.1 on 2026-06-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0015_reservation_statut_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('date_besoin', models.DateField()),
                ('marche', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.commercant')),
            ],
        ),
    ]
