# Generated by Django 6.0.1 on 2026-06-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0016_demandemarche'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandemarche',
            name='producteur_engage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_engagees', to='gestion_agro.producteur'),
        ),
        migrations.AddField(
            model_name='demandemarche',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Ouverte'), ('ATTRIBUEE', 'Attribuée'), ('SATISFAITE', 'Satisfaite')], default='OUVERTE', max_length=20),
        ),
    ]
