# Generated by Django 6.0.1 on 2026-06-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0017_demandemarche_producteur_engage_demandemarche_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemarche',
            name='commercant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='gestion_agro.commercant'),
        ),
    ]
