# Generated by Django 6.0.1 on 2026-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0018_alter_demandemarche_commercant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemarche',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Ouverte'), ('ATTRIBUEE', 'Attribuée'), ('SATISFAITE', 'Satisfaite'), ('EXPIREE', 'Expirée')], default='OUVERTE', max_length=20),
        ),
    ]
