# Generated by Django 6.0.1 on 2026-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0019_alter_demandemarche_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='score_fiabilite',
            field=models.IntegerField(default=100),
        ),
    ]
