# Generated by Django 6.0.1 on 2026-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0020_transporteur_score_fiabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='preuve_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='preuves_paiement/', verbose_name='Photo du reçu / SMS'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_caution',
            field=models.CharField(choices=[('NON_PAYE', 'Non payée'), ('ATTENTE_VALIDATION', 'En attente de validation'), ('PAYE', 'Payée'), ('BLOQUEE', 'Bloquée'), ('LIBEREE', 'Libérée')], default='NON_PAYE', max_length=30),
        ),
    ]
