# Generated by Django 6.0.1 on 2026-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0021_reservation_preuve_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut_reste',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('DECLARE', 'Déclaré payé'), ('CONFIRME', 'Confirmé par le producteur'), ('LITIGE', 'En litige')], default='NON_PAYE', max_length=20),
        ),
    ]
