# Generated by Django 6.0.1 on 2026-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0022_reservation_statut_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='numero_piece',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='piece_identite',
            field=models.ImageField(blank=True, null=True, upload_to='pieces_identite/'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='type_piece',
            field=models.CharField(choices=[('CARTE_IDENTITE', "Carte d'identité"), ('CARTE_BIOMETRIQUE', 'Carte biométrique'), ('PASSEPORT', 'Passeport'), ('CARTE_ELECTEUR', "Carte d'électeur"), ('AUTRE', 'Autre')], default='CARTE_IDENTITE', max_length=30),
        ),
    ]
