# Generated by Django 6.0.1 on 2026-06-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0025_commercant_est_verifie_commercant_numero_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercant',
            name='type_piece',
            field=models.CharField(choices=[('CARTE_IDENTITE', "Carte d'identité"), ('CARTE_BIOMETRIQUE', 'Carte biométrique/Nina'), ('PASSEPORT', 'Passeport')], default='CARTE_IDENTITE', max_length=30),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='type_piece',
            field=models.CharField(choices=[('CARTE_IDENTITE', "Carte d'identité"), ('CARTE_BIOMETRIQUE', 'Carte biométrique/Nina'), ('PASSEPORT', 'Passeport')], default='CARTE_IDENTITE', max_length=30),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='type_piece',
            field=models.CharField(choices=[('CARTE_IDENTITE', "Carte d'identité"), ('CARTE_BIOMETRIQUE', 'Carte biométrique/Nina'), ('PASSEPORT', 'Passeport')], default='CARTE_IDENTITE', max_length=30),
        ),
    ]
