# Generated by Django 6.0.1 on 2026-06-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0027_categorie_produitagricole_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitagricole',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
