# Generated by Django 6.0.1 on 2026-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0028_remove_produitagricole_categorie_delete_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitagricole',
            name='categorie',
            field=models.CharField(choices=[('LEGUMES', '🥬 Légumes'), ('FRUITS', '🍎 Fruits'), ('CEREALES', '🌾 Céréales'), ('TUBERCULES', '🥔 Tubercules')], default='LEGUMES', max_length=20),
        ),
    ]
