# Generated by Django 6.0.1 on 2026-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0029_produitagricole_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='tarif_propose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
