# Generated by Django 6.0.1 on 2026-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0030_livraison_tarif_propose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('proposition', 'Tarif proposé - En attente'), ('accepte', 'Accepté par le commerçant'), ('refuse', 'Refusé par le commerçant'), ('en_attente', 'En attente de chargement'), ('en_route', 'En route'), ('livre', 'Livré')], default='en_attente', max_length=20),
        ),
    ]
