# Generated by Django 6.0.1 on 2026-06-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0031_alter_livraison_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercant',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
    ]
