# Generated by Django 6.0.1 on 2026-06-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0032_commercant_est_actif_producteur_est_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('CAUTION', 'Caution reçue'), ('REMBOURSEMENT', 'Remboursement commerçant'), ('Paiement', 'Paiement producteur')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EFFECTUE', 'Effectué')], default='EN_ATTENTE', max_length=20)),
                ('date_execution', models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution")),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gestion_agro.reservation')),
            ],
        ),
    ]
