# Generated by Django 6.0.1 on 2026-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0033_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('CAUTION', 'Caution reçue'), ('REMBOURSEMENT', 'Remboursement commerçant'), ('Paiement', 'Paiement producteur'), ('GAIN_TRANSPORT', 'Gain du transporteur')], max_length=20),
        ),
    ]
