# Generated by Django 6.0.1 on 2026-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0034_alter_transaction_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='capacite_kg',
            field=models.PositiveIntegerField(default=10000, verbose_name='Capacité du camion (kg)'),
        ),
    ]
